image: gitlab.hoztnode.net:4598/rnd/cloru/cloapi-go-client/golang:latest

stages:
  - test

test:
  stage: test
  script:
    - go get github.com/boumenot/gocover-cobertura
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -coverprofile=coverage.txt -covermode count $(go list ./... | grep -v /vendor/)
    - $GOPATH/bin/gocover-cobertura < target/coverage/cli_coverage.out > target/coverage/cli_coverage.xml
  coverage:  '/^coverage: (\d+.\d+)% of statements$/'

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml